# Generated by Django 3.1.2 on 2020-11-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('review', models.TextField()),
                ('신선도', models.IntegerField()),
                ('배송', models.IntegerField()),
                ('가격', models.IntegerField()),
                ('품질', models.IntegerField()),
                ('정확성', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
